### ISSUE TITLE
Quest 2 - Oversleeping Doctor

### ISSUE THREAD

**Issue by porkbob** [Kyuuhachi/Inevitable-Zero#1]
Another string that overextends the text box bounds in the 2nd Vita quest at St Ursula. When you talk to Receptionist Sera at the front desk, her message "I M P O S S I B L E !" does it.

Also if there is supposed to be a sound of the bus engine playing when you're inside the bus during this quest, it doesn't play and leaves several seconds of awkward silence before the music kicks in.

**Comment by Kyuuhachi** [comment]
Done. Turns out the text engine doesn't like putting size change instructions at the end of a line (even though Joyo and Vita handled that just fine), so I've manually moved them now. There were a few instances in later quests too, but they're also fixed now. Except possibly one in the Showdown aftermath which switches font size in the middle of a line, we'll see if that still works.

The sound was, once again, that I translated the PLAY_SOUND instruction wrong. Oh well, not a difficult fix this time either.

**Comment by porkbob** [comment]
Even more of a minor thing, but just in case you want to know—at the beginning of Chapter 3 when you can go and see the results of Vita quest 1, if the result is a draw Morges has a line where he says "Neither! it's a draw" with a font size change mid-line. This works fine in the normal cutscene because the box is plenty more than big enough, but if you go back into the message log, that line is then overhanging the box because it is much smaller.

**Comment by Kyuuhachi** [comment]
Yeah, I kinda expected that one to be trouble. Maybe I should stick a line break in there.
